# Site settings
title: Noot's blog
email: nootfy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website includes some programming tips and useful information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nootfly.github.io" # the base hostname & protocol for your site
twitter_username: noot
github_username:  nootfly

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
disqus_shortname: nootfly
show_sharing_icons: true
share_facebook: true
share_twitter: true
share_linkedin: true
share_digg: true
share_reddit: true
share_hackernews: true
comments: true
